image: docker:latest
services:
  - docker:dind

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

before_script:
  - apk add --no-cache gradle
  - docker info
  - export GRADLE_USER_HOME=`pwd` gradle

stages:
  - build
  - test

build:
  stage: build
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle


job_tests:
  stage: test
  script:
    - 'gradle clean test jacocoTestReport'
  artifacts:
    when: always
    paths:
      - build/reports/jacoco/test
    reports:
      junit: build/test-results/test/*.xml
      coverage_report:
        coverage_format: cobertura
        path: build/reports/jacoco/test/jacocoTestReport.xml